# NumPy #

https://numpy.org

NumPy is the fundamental package for scientific computing with Python. It contains among other things:

* a powerful N-dimensional array object
* sophisticated (broadcasting) functions
* tools for integrating C/C++ and Fortran code
* useful linear algebra, Fourier transform, and random number capabilities


## Introduction

In [1]:
import numpy as np
print(np.__version__)

1.17.2


In [2]:
a = np.array([0, 1, 2, 3])
print(a)

[0 1 2 3]


In [3]:
L = range(1000)
%timeit [i**2 for i in L]

280 µs ± 431 ns per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [4]:
a = np.arange(1000)
%timeit a**2

1.21 µs ± 15.3 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [17]:
# numpy
# np.lookfor('eigen')# uncomment me to try

In [20]:
# jupyter
# np.con*?# uncomment me to try

In [21]:
# jupyter
# np.concatenate?# uncomment me to try

## Creating arrays

### Manual construction
* numpy.array()

In [22]:
a = np.array([0, 1, 2, 3])
a

array([0, 1, 2, 3])

In [23]:
print(a)

[0 1 2 3]


In [24]:
repr(a)

'array([0, 1, 2, 3])'

In [25]:
str(a)

'[0 1 2 3]'

In [26]:
a.ndim

1

In [27]:
a.shape

(4,)

In [28]:
len(a)

4

In [29]:
b = np.array([[0, 1, 2], [3, 4, 5]])
b

array([[0, 1, 2],
       [3, 4, 5]])

In [30]:
print(b)

[[0 1 2]
 [3 4 5]]


In [31]:
b.ndim

2

In [32]:
b.shape

(2, 3)

In [33]:
len(b)

2

In [34]:
c = np.array([[[1], [2]], [[3], [4]]])
c

array([[[1],
        [2]],

       [[3],
        [4]]])

In [35]:
c.ndim

3

In [36]:
c.shape

(2, 2, 1)

In [37]:
len(c)

2

In [38]:
d = np.array([[1],[2],[3],[4]])
d

array([[1],
       [2],
       [3],
       [4]])

In [39]:
d.ndim

2

In [40]:
d.shape

(4, 1)

### Functions for creating arrays
* numpy.arange()
* numpy.linspace()
* numpy.ones()
* numpy.zeros()
* numpy.eye()
* numpy.empty()
* numpy.full()
* numpy.ones_like()
* numpy.zeros_like()
* numpy.empty_like()
* numpy.full_like()

In [41]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
b = np.arange(1, 9, 2)
b

array([1, 3, 5, 7])

In [43]:
c = np.linspace(0, 1, 11)
c

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [44]:
a = np.ones((3, 3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [45]:
b = np.zeros((2, 2))
b

array([[0., 0.],
       [0., 0.]])

In [46]:
c = np.eye(3)
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [47]:
a = np.empty([2, 2])
a

array([[0., 0.],
       [0., 0.]])

In [48]:
a = np.full((2, 2), 1.23)
a

array([[1.23, 1.23],
       [1.23, 1.23]])

In [49]:
a = np.ones((3, 3))
print(a)
b = np.zeros_like(a)
b

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## Indexing and slicing

## Matrix multiplication
numpy.matrix()
**It is no longer recommended to use this class, even for linear algebra. Instead use regular arrays. The class may be removed in the future.**

* numpy.matmul()
* numpy.dot()
* numpy.vdot()
* numpy.tensordot()

### `numpy.dot(1D, 1D)` --> inner product of vectors (without complex conjugation)

In [50]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.dot(a, b)

32

In [51]:
a = np.array([2j, 3j])
b = np.array([2j, 3j])
np.dot(a, b)

(-13+0j)

### `numpy.vdot(1D, 1D)` --> inner product of vectors (complex conjugate of the first argument is used)

In [52]:
a = np.array([2j, 3j])
b = np.array([2j, 3j])
np.vdot(a, b)

(13+0j)

### `numpy.matmul(2D, 2D)` --> matrix multiplication

In [53]:
a = np.array([[1, 0],
              [0, 1]])
b = np.array([[4, 1],
              [2, 2]])
np.matmul(a, b)

array([[4, 1],
       [2, 2]])

In [54]:
a @ b 

array([[4, 1],
       [2, 2]])

### `numpy.matmul(2D, 1D)` or `numpy.matmul(1D, 2D)`--> matrix multiplication

In [55]:
a = np.array([[1, 2],
              [0, 1]])
b = np.array([1, 2])
b.shape

(2,)

In [56]:
np.matmul(a, b)

array([5, 2])

In [57]:
a @ b

array([5, 2])

In [58]:
np.matmul(b, a)

array([1, 4])

In [37]:
b @ a 

array([1, 4])

In [41]:
a = np.array([[1, 2],
              [0, 1]])
b = np.array([[1], [2]])
print(b)
b.shape

[[1]
 [2]]


(2, 1)

In [42]:
np.matmul(a, b)

array([[5],
       [2]])

In [43]:
a @ b

array([[5],
       [2]])

In [44]:
np.matmul(b, a)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 1)

In [45]:
b @ a 

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 1)

## Linear Algebra ##

### Determinant

In [51]:
a = np.array([[1, 2], [3, 4]])
np.linalg.det(a)

-2.0000000000000004

## Numerical operations on arrays

In [46]:
a = np.array([1, 2, 3, 4])
a + 1 

array([2, 3, 4, 5])

In [53]:
x = np.linspace(0, np.pi, 10)
x

array([0.        , 0.34906585, 0.6981317 , 1.04719755, 1.3962634 ,
       1.74532925, 2.0943951 , 2.44346095, 2.7925268 , 3.14159265])

In [54]:
np.sin(x)

array([0.00000000e+00, 3.42020143e-01, 6.42787610e-01, 8.66025404e-01,
       9.84807753e-01, 9.84807753e-01, 8.66025404e-01, 6.42787610e-01,
       3.42020143e-01, 1.22464680e-16])