# NumPy

In [1]:
import numpy as np
import matplotlib.pyplot as plt
print(np.__version__)

1.17.2


In [2]:
import matplotlib
print(matplotlib.__version__)

3.1.1


## Linear Algebra

### Matrix multiplication
numpy.matrix()
**It is no longer recommended to use this class, even for linear algebra. Instead use regular arrays. The class may be removed in the future.**

* numpy.matmul()
* numpy.dot()
* numpy.vdot()
* numpy.tensordot()

#### `numpy.dot(1D, 1D)` --> inner product of vectors (without complex conjugation)

In [3]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.dot(a, b)

32

In [4]:
a = np.array([2j, 3j])
b = np.array([2j, 3j])
np.dot(a, b)

(-13+0j)

#### `numpy.vdot(1D, 1D)` --> inner product of vectors (complex conjugate of the first argument is used)

In [5]:
a = np.array([2j, 3j])
b = np.array([2j, 3j])
np.vdot(a, b)

(13+0j)

### `numpy.matmul(2D, 2D)` --> matrix multiplication

In [6]:
a = np.array([[1, 0],
              [0, 1]])
b = np.array([[4, 1],
              [2, 2]])
np.matmul(a, b)

array([[4, 1],
       [2, 2]])

#### Use '@' operator

In [7]:
a = np.array([[1, 0],
              [0, 1]])
b = np.array([[4, 1],
              [2, 2]])
a @ b 

array([[4, 1],
       [2, 2]])

#### `numpy.matmul(2D, 1D)` or `numpy.matmul(1D, 2D)`--> matrix multiplication

In [8]:
a = np.array([[1, 2],
              [0, 1]])
b = np.array([1, 2])
b.shape

(2,)

In [9]:
np.matmul(a, b)

array([5, 2])

In [10]:
a @ b

array([5, 2])

In [11]:
np.matmul(b, a)

array([1, 4])

In [12]:
b @ a 

array([1, 4])

In [13]:
a = np.array([[1, 2],
              [0, 1]])
b = np.array([[1], [2]])
print(b)
b.shape

[[1]
 [2]]


(2, 1)

In [14]:
np.matmul(a, b)

array([[5],
       [2]])

In [15]:
a @ b

array([[5],
       [2]])

In [16]:
np.matmul(b, a)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 1)

In [17]:
b @ a 

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 1)

### Determinant

In [18]:
a = np.array([[1, 2], [3, 4]])
np.linalg.det(a)

-2.0000000000000004